export const ACADEMY_LESSONS = [
  {
    id: "tahvil-faizi-nasdaq",
    category: "Makro",
    title: "Tahvil Faizleri NASDAQ Hisselerini Neden Etkiler?",
    duration: "7 dk",
    level: "Başlangıç",
    summary: "Tahvil faizleri yükseldiğinde gelecekte elde edilmesi beklenen şirket kârlarının bugünkü değeri düşebilir. Bu nedenle yüksek büyüme beklentili teknoloji hisseleri faiz hareketlerine daha hassastır.",
    points: ["Faiz yükselişi alternatif getiriyi artırır.", "Uzak gelecekteki kârların bugünkü değeri azalabilir.", "Büyüme hisselerinde değerleme baskısı oluşabilir."],
    example: "10 yıllık ABD tahvil faizi sert yükselirken NASDAQ endeksinin baskı altında kalması bu ilişkinin sık görülen örneğidir.",
    term: "Tahvil getirisi",
    definition: "Bir tahvili elde tutan yatırımcının fiyat ve faiz ödemeleri üzerinden beklediği getiridir.",
    question: "Tahvil faizleri hızla yükseldiğinde hangi grup genellikle daha hassas olabilir?",
    options: ["Yüksek büyüme hisseleri", "Sadece nakit tutan şirketler", "Hiçbir şirket"],
    answer: 0,
    explanation: "Yüksek büyüme hisselerinin değerinin daha büyük bölümü gelecekte beklenen kârlara dayanır."
  },
  {
    id: "fiyat-kazanc-orani",
    category: "Değerleme",
    title: "Fiyat/Kazanç Oranı Nasıl Okunur?",
    duration: "6 dk",
    level: "Başlangıç",
    summary: "F/K oranı yatırımcının şirketin bir yıllık hisse başına kârının kaç katını ödediğini gösterir. Tek başına ucuzluk veya pahalılık kararı vermek için yeterli değildir.",
    points: ["F/K sektör ortalamasıyla kıyaslanmalıdır.", "Büyüme hızı yüksek şirketlerde oran yüksek olabilir.", "Geçici kâr düşüşleri oranı yanıltabilir."],
    example: "F/K oranı 30 olan bir şirket, mevcut yıllık kârının 30 katı piyasa değeriyle fiyatlanıyor demektir.",
    term: "F/K oranı",
    definition: "Hisse fiyatının hisse başına kâra bölünmesiyle hesaplanan değerleme oranıdır.",
    question: "Yüksek F/K oranı tek başına neyi kanıtlar?",
    options: ["Hissenin kesin düşeceğini", "Şirketin iflas edeceğini", "Kesin bir sonuç kanıtlamaz"],
    answer: 2,
    explanation: "F/K büyüme, sektör, faiz ve kâr kalitesiyle birlikte değerlendirilmelidir."
  },
  {
    id: "gelir-ve-kar",
    category: "Bilanço",
    title: "Gelir Artışı ile Kâr Artışı Aynı Şey Değildir",
    duration: "6 dk",
    level: "Başlangıç",
    summary: "Şirket satışlarını artırırken maliyetleri daha hızlı yükseliyorsa gelir büyüse bile net kâr düşebilir. Bu nedenle bilanço okurken yalnızca ciroya bakılmaz.",
    points: ["Gelir şirketin satış büyüklüğünü gösterir.", "Brüt ve faaliyet marjları maliyet kontrolünü gösterir.", "Net kâr finansman ve vergi giderlerinden etkilenir."],
    example: "Geliri yüzde 20 büyüyen fakat maliyetleri yüzde 30 artan bir şirketin kârlılığı zayıflayabilir.",
    term: "Net kâr marjı",
    definition: "Net kârın toplam gelire oranıdır ve her 100 birim satıştan ne kadar kâr kaldığını gösterir.",
    question: "Gelir yükselirken net kâr neden düşebilir?",
    options: ["Maliyetler daha hızlı arttığı için", "Hisse kodu değiştiği için", "İşlem hacmi düştüğü için"],
    answer: 0,
    explanation: "Satış büyümesi ancak maliyetler kontrol altında tutulduğunda kâra güçlü biçimde yansır."
  },
  {
    id: "brut-kar-marji",
    category: "Bilanço",
    title: "Brüt Kâr Marjı Şirketin Gücünü Nasıl Gösterir?",
    duration: "6 dk",
    level: "Orta",
    summary: "Brüt kâr marjı ürün veya hizmet üretmenin doğrudan maliyeti çıktıktan sonra kalan payı gösterir. Marjın yükselmesi fiyatlama gücüne veya maliyet avantajına işaret edebilir.",
    points: ["Marj değişimi geçmiş dönemlerle kıyaslanmalıdır.", "Sektörler arasında doğal marj farkları vardır.", "Sürekli düşen marj rekabet baskısını gösterebilir."],
    example: "Brüt marjı yüzde 40’tan yüzde 45’e çıkan bir şirket her 100 dolarlık satıştan daha fazla brüt kâr bırakır.",
    term: "Brüt kâr",
    definition: "Gelirden satılan ürün veya hizmetin doğrudan maliyeti çıkarıldıktan sonra kalan tutardır.",
    question: "Brüt kâr marjının yükselmesi ne gösterebilir?",
    options: ["Fiyatlama gücünün arttığını", "Şirketin gelir üretmediğini", "Hissenin işlem görmediğini"],
    answer: 0,
    explanation: "Yükselen brüt marj şirketin ürünlerini daha kârlı sattığını gösterebilir."
  },
  {
    id: "guidance",
    category: "Bilanço",
    title: "Guidance Neden Bilanço Kadar Önemlidir?",
    duration: "7 dk",
    level: "Orta",
    summary: "Guidance yönetimin gelecek dönem için açıkladığı gelir, kâr ve yatırım beklentileridir. Piyasa geçmiş sonuçlardan çok geleceğe odaklandığı için güçlü bilanço sonrası bile zayıf guidance düşüş getirebilir.",
    points: ["Beklentinin yönü fiyatlamayı etkiler.", "Yönetimin güveni yatırımcı algısını değiştirir.", "Tahminlerdeki revizyonlar yakından izlenir."],
    example: "Beklentiyi aşan kâr açıklayan bir şirket gelecek çeyrek satış tahminini düşürürse hissesi gerileyebilir.",
    term: "Guidance",
    definition: "Şirket yönetiminin gelecek dönem performansı için yayımladığı öngörüdür.",
    question: "Güçlü bilanço sonrası hisse neden düşebilir?",
    options: ["Gelecek dönem beklentisi zayıfsa", "Şirket adı uzunsa", "Borsa açık olduğu için"],
    answer: 0,
    explanation: "Fiyatlar çoğunlukla gelecekte beklenen sonuçları önceden satın alır."
  },
  {
    id: "hisse-basina-kar",
    category: "Bilanço",
    title: "Hisse Başına Kâr ve Beklenti Sürprizi",
    duration: "6 dk",
    level: "Başlangıç",
    summary: "Hisse başına kâr şirketin net kârının hisse sayısına bölünmüş hâlidir. Açıklanan sonuç analist beklentisinin üzerindeyse pozitif sürpriz oluşabilir.",
    points: ["EPS kısaltmasıyla gösterilir.", "Hisse sayısındaki değişim EPS değerini etkiler.", "Tek seferlik gelirler sonucu şişirebilir."],
    example: "Beklenti 1,20 dolar iken 1,45 dolar EPS açıklanması olumlu kâr sürprizidir.",
    term: "EPS",
    definition: "İngilizce Earnings Per Share ifadesinin kısaltmasıdır ve hisse başına kâr anlamına gelir.",
    question: "EPS hesaplanırken net kâr hangi değere bölünür?",
    options: ["Toplam çalışan sayısına", "Hisse sayısına", "Günlük işlem hacmine"],
    answer: 1,
    explanation: "EPS, şirket kârının her bir hisseye düşen bölümünü ölçer."
  },
  {
    id: "nakit-akisi",
    category: "Bilanço",
    title: "Kâr Var Ama Nakit Yoksa Ne Anlama Gelir?",
    duration: "8 dk",
    level: "Orta",
    summary: "Muhasebe kârı ile kasaya giren gerçek nakit aynı olmayabilir. Sağlıklı bir şirkette faaliyetlerden üretilen nakdin zaman içinde kârı desteklemesi beklenir.",
    points: ["Alacaklardaki artış nakdi geciktirebilir.", "Stok büyümesi nakit tüketebilir.", "Serbest nakit akışı yatırım kapasitesini gösterir."],
    example: "Satışını vadeli yapan şirket gelir yazabilir fakat müşteriden ödeme gelene kadar nakit oluşmaz.",
    term: "Serbest nakit akışı",
    definition: "Faaliyet nakdinden gerekli sermaye harcamaları çıkarıldıktan sonra kalan nakittir.",
    question: "Muhasebe kârı oluştuğu hâlde nakit neden zayıf kalabilir?",
    options: ["Tahsilatlar geciktiği için", "Logo değiştiği için", "Borsa kapalı olduğu için"],
    answer: 0,
    explanation: "Vadeli satışlar gelir yaratırken nakdin şirkete daha sonra girmesine neden olabilir."
  },
  {
    id: "borc-ve-faiz",
    category: "Risk",
    title: "Şirket Borcu Ne Zaman Tehlikeli Olur?",
    duration: "7 dk",
    level: "Orta",
    summary: "Borç tek başına kötü değildir; önemli olan şirketin borcu ödeme kapasitesi ve borcun maliyetidir. Faiz yükseldikçe yüksek borçlu şirketlerin finansman gideri artabilir.",
    points: ["Net borç, nakit düşüldükten sonraki borcu gösterir.", "Faiz karşılama oranı ödeme gücünü ölçer.", "Kısa vadeli borçlar likidite riski yaratabilir."],
    example: "Nakit üretimi zayıf ve yakın vadede yüksek borç ödemesi olan şirket daha kırılgan olabilir.",
    term: "Net borç",
    definition: "Toplam finansal borçtan şirketin nakit ve nakit benzerleri çıkarılarak hesaplanır.",
    question: "Faizler yükseldiğinde yüksek borçlu şirket neden zorlanabilir?",
    options: ["Finansman gideri artabileceği için", "Hisse kodu kısaldığı için", "Geliri otomatik arttığı için"],
    answer: 0,
    explanation: "Borç yenileme ve faiz ödemesi maliyetleri şirket kârını baskılayabilir."
  },
  {
    id: "sermaye-artirimi",
    category: "Risk",
    title: "Yeni Hisse İhracı Neden Sulandırma Yaratır?",
    duration: "7 dk",
    level: "Orta",
    summary: "Şirket yeni hisse çıkardığında toplam hisse sayısı artar. Mevcut yatırımcının şirket içindeki yüzde payı ve hisse başına düşen değer azalabilir.",
    points: ["Toplanan paranın kullanım amacı önemlidir.", "Büyüme yatırımı uzun vadede değer yaratabilir.", "Sık sermaye artırımı finansman sorununa işaret edebilir."],
    example: "100 hisseli şirket 20 yeni hisse çıkarırsa eski yatırımcının ortaklık oranı azalır.",
    term: "Sulandırma",
    definition: "Yeni hisse ihracı nedeniyle mevcut hisselerin şirket üzerindeki oransal payının azalmasıdır.",
    question: "Yeni hisse ihracında hangi değer doğrudan artar?",
    options: ["Toplam hisse sayısı", "Her zaman net kâr", "Her zaman temettü"],
    answer: 0,
    explanation: "Yeni ihraç edilen hisseler dolaşımdaki toplam hisse sayısını artırır."
  },
  {
    id: "hisse-geri-alimi",
    category: "Sermaye",
    title: "Hisse Geri Alımı Yatırımcı İçin Ne İfade Eder?",
    duration: "6 dk",
    level: "Başlangıç",
    summary: "Şirket kendi hisselerini geri aldığında dolaşımdaki hisse sayısı azalabilir. Bu durum aynı kâr seviyesinde hisse başına kârı yükseltebilir.",
    points: ["Geri alım fiyatının makul olması önemlidir.", "Borçla yapılan geri alım riski artırabilir.", "Yönetimin şirkete güven sinyali olabilir."],
    example: "Net kâr değişmezken hisse sayısı azalırsa EPS yükselebilir.",
    term: "Geri alım programı",
    definition: "Şirketin piyasadan kendi hisselerini belirli koşullarla satın alma planıdır.",
    question: "Hisse sayısı azalırken net kâr sabit kalırsa EPS genellikle ne olur?",
    options: ["Yükselir", "Sıfırlanır", "Her zaman düşer"],
    answer: 0,
    explanation: "Aynı kâr daha az sayıda hisseye bölündüğü için hisse başına kâr artabilir."
  },
  {
    id: "hacim",
    category: "Teknik Analiz",
    title: "İşlem Hacmi Fiyat Hareketini Nasıl Doğrular?",
    duration: "6 dk",
    level: "Başlangıç",
    summary: "İşlem hacmi belirli sürede el değiştiren hisse miktarını gösterir. Güçlü hacimle gerçekleşen kırılımlar, düşük hacimli hareketlere göre daha fazla katılım içerir.",
    points: ["Hacim geçmiş ortalamayla kıyaslanmalıdır.", "Yükselişte artan hacim talebi destekleyebilir.", "Tek günlük hacim tek başına yeterli değildir."],
    example: "Direncini ortalamanın üç katı hacimle aşan hisse daha geniş yatırımcı katılımı göstermiş olabilir.",
    term: "Ortalama hacim",
    definition: "Belirli sayıdaki işlem gününün hacimlerinin ortalamasıdır.",
    question: "Hacim en doğru nasıl değerlendirilir?",
    options: ["Geçmiş ortalamayla kıyaslanarak", "Sadece hisse fiyatına bakılarak", "Şirket logosuna göre"],
    answer: 0,
    explanation: "Hacmin olağan dışı olup olmadığı ancak kendi geçmişiyle kıyaslandığında anlaşılır."
  },
  {
    id: "destek-direnc",
    category: "Teknik Analiz",
    title: "Destek ve Direnç Seviyeleri Nasıl Kullanılır?",
    duration: "7 dk",
    level: "Başlangıç",
    summary: "Destek alıcıların güçlenebildiği, direnç ise satıcıların yoğunlaşabildiği fiyat bölgeleridir. Bunlar kesin çizgiler değil, olasılık bölgeleridir.",
    points: ["Seviyeler bölge olarak düşünülmelidir.", "Kırılım hacimle doğrulanabilir.", "Eski direnç daha sonra destek olabilir."],
    example: "Bir hisse birkaç kez 50 dolardan dönmüşse bu alan direnç bölgesi kabul edilebilir.",
    term: "Kırılım",
    definition: "Fiyatın önemli destek veya direnç bölgesinin dışına hareket etmesidir.",
    question: "Destek ve direnç için hangisi doğrudur?",
    options: ["Kesin sonuç garantiler", "Olasılık bölgesidir", "Sadece günlük grafikte vardır"],
    answer: 1,
    explanation: "Piyasa seviyeleri kesinlik değil, yatırımcı davranışının yoğunlaştığı bölgeleri gösterir."
  },
  {
    id: "hareketli-ortalama",
    category: "Teknik Analiz",
    title: "EMA20, EMA50 ve EMA200 Ne Anlatır?",
    duration: "7 dk",
    level: "Orta",
    summary: "Hareketli ortalamalar fiyatın belirli dönemdeki eğilimini yumuşatarak gösterir. Kısa ve uzun vadeli ortalamaların konumu trend hakkında fikir verebilir.",
    points: ["EMA20 kısa vadeye daha duyarlıdır.", "EMA50 orta vadeli eğilimi izler.", "EMA200 uzun vadeli ana trend için kullanılır."],
    example: "Fiyat EMA200 üzerinde kalırken yükselen EMA50 orta ve uzun vadeli güce işaret edebilir.",
    term: "Üssel hareketli ortalama",
    definition: "Son fiyatlara daha fazla ağırlık veren hareketli ortalama türüdür.",
    question: "Uzun vadeli ana trend için en sık hangisi izlenir?",
    options: ["EMA5", "EMA20", "EMA200"],
    answer: 2,
    explanation: "EMA200 yaklaşık 200 işlem günlük uzun vadeli eğilimi temsil eder."
  },
  {
    id: "rsi",
    category: "Teknik Analiz",
    title: "RSI Aşırı Alım Demek Hemen Satış Demek midir?",
    duration: "7 dk",
    level: "Orta",
    summary: "RSI fiyat hareketinin hızını ölçen momentum göstergesidir. 70 üzeri aşırı alım kabul edilse de güçlü trendlerde RSI uzun süre yüksek kalabilir.",
    points: ["RSI tek başına işlem sinyali değildir.", "Uyumsuzluklar momentum değişimini gösterebilir.", "Trend ve destek seviyeleriyle birlikte okunmalıdır."],
    example: "Güçlü yükseliş trendindeki bir hisse RSI 70 üzerinde haftalarca kalabilir.",
    term: "Momentum",
    definition: "Fiyat hareketinin hızını ve devam gücünü ifade eder.",
    question: "RSI 70 üzerine çıktığında ne yapılmalıdır?",
    options: ["Kesinlikle hemen satılmalıdır", "Diğer verilerle birlikte değerlendirilmelidir", "Veri görmezden gelinmelidir"],
    answer: 1,
    explanation: "Aşırı alım göstergesi trendin hemen biteceğini garanti etmez."
  },
  {
    id: "piyasa-degeri",
    category: "Temel Analiz",
    title: "Hisse Fiyatı ile Şirket Değeri Aynı Şey Değildir",
    duration: "6 dk",
    level: "Başlangıç",
    summary: "Tek bir hissenin fiyatı şirketin ucuz veya pahalı olduğunu göstermez. Şirket değeri, hisse fiyatının toplam hisse sayısıyla çarpılmasıyla ölçülür.",
    points: ["Düşük fiyatlı hisse büyük şirket olabilir.", "Hisse bölünmesi şirket değerini değiştirmez.", "Kıyaslamada piyasa değeri kullanılmalıdır."],
    example: "10 dolarlık bir hissenin şirketi, 500 dolarlık başka bir hissenin şirketinden daha büyük olabilir.",
    term: "Piyasa değeri",
    definition: "Hisse fiyatı ile dolaşımdaki toplam hisse sayısının çarpımıdır.",
    question: "Bir şirketin borsadaki toplam değeri nasıl hesaplanır?",
    options: ["Fiyat × hisse sayısı", "Fiyat × çalışan sayısı", "Gelir ÷ hacim"],
    answer: 0,
    explanation: "Tek hisse fiyatı değil, toplam hisse sayısıyla birlikte piyasa değeri oluşur."
  },
  {
    id: "beta",
    category: "Risk",
    title: "Beta Hissenin Riskini Nasıl Gösterir?",
    duration: "6 dk",
    level: "Orta",
    summary: "Beta, hissenin piyasa hareketlerine karşı tarihsel duyarlılığını ölçer. Beta 1 üzerindeyse hisse genellikle piyasadan daha oynak davranmıştır.",
    points: ["Beta geçmiş verilere dayanır.", "Yüksek beta hem kazanç hem kayıp hızını artırabilir.", "Şirkete özel riskleri tek başına ölçmez."],
    example: "Beta değeri 1,5 olan hisse, geçmişte piyasa yüzde 1 hareket ettiğinde ortalama daha sert hareket etmiş olabilir.",
    term: "Beta",
    definition: "Bir varlığın piyasa endeksine göre tarihsel oynaklık katsayısıdır.",
    question: "Beta değeri 1’den büyükse genel olarak ne söylenebilir?",
    options: ["Piyasadan daha oynak olabilir", "Hiç hareket etmez", "Kesin kazandırır"],
    answer: 0,
    explanation: "Yüksek beta piyasa hareketlerine daha güçlü tepki olasılığını ifade eder."
  },
  {
    id: "call-put",
    category: "Opsiyon",
    title: "Call ve Put Opsiyonlarının Temel Mantığı",
    duration: "8 dk",
    level: "Başlangıç",
    summary: "Call opsiyonu belirli fiyattan alma, put opsiyonu ise belirli fiyattan satma hakkı verir. Opsiyon alıcısı bu hak için prim öder.",
    points: ["Call yükseliş beklentisiyle ilişkilidir.", "Put düşüş beklentisi veya korunma için kullanılabilir.", "Opsiyonların vade tarihi vardır."],
    example: "Bir yatırımcı elindeki hisseyi düşüşe karşı korumak için put opsiyonu kullanabilir.",
    term: "Kullanım fiyatı",
    definition: "Opsiyon sözleşmesinde alım veya satım hakkının kullanılabileceği fiyattır.",
    question: "Put opsiyonu hangi hakkı verir?",
    options: ["Belirli fiyattan satma", "Temettüyü artırma", "Şirket yönetimine girme"],
    answer: 0,
    explanation: "Put opsiyonu sahibine dayanak varlığı kullanım fiyatından satma hakkı verir."
  },
  {
    id: "ima-edilen-oynaklik",
    category: "Opsiyon",
    title: "İma Edilen Oynaklık Neden Önemlidir?",
    duration: "8 dk",
    level: "Orta",
    summary: "İma edilen oynaklık piyasanın gelecekte beklediği hareket büyüklüğünü opsiyon fiyatlarından yansıtır. Yüksek değer yönü değil, büyük hareket beklentisini gösterir.",
    points: ["Yüksek oynaklık opsiyon primini artırabilir.", "Bilanço öncesi yükselmesi sık görülür.", "Hareketin yönünü tek başına söylemez."],
    example: "Bilanço öncesi hem call hem put primlerinin yükselmesi büyük hareket beklentisini gösterebilir.",
    term: "İma edilen oynaklık",
    definition: "Opsiyon fiyatlarının içerdiği gelecekteki beklenen oynaklık ölçüsüdür.",
    question: "Yüksek ima edilen oynaklık neyi kesin olarak göstermez?",
    options: ["Büyük hareket beklentisini", "Hareketin yönünü", "Opsiyon priminin etkilenebileceğini"],
    answer: 1,
    explanation: "Oynaklık hareketin büyüklüğüyle ilgilidir; yukarı veya aşağı yönü garanti etmez."
  },
  {
    id: "fed-faizi",
    category: "Makro",
    title: "FED Faiz Kararı Piyasayı Nasıl Etkiler?",
    duration: "8 dk",
    level: "Orta",
    summary: "FED politika faizi finansman maliyetini, tahvil getirilerini ve risk iştahını etkiler. Kararın kendisi kadar geleceğe yönelik açıklamalar da önemlidir.",
    points: ["Faiz artışı finansmanı pahalılaştırabilir.", "Faiz indirimi risk iştahını destekleyebilir.", "Piyasa çoğu zaman beklentiyi önceden fiyatlar."],
    example: "FED faizi sabit bıraksa bile şahin açıklamalar tahvil faizlerini yükseltebilir.",
    term: "Şahin tutum",
    definition: "Merkez bankasının enflasyonla mücadele için daha sıkı para politikasını destekleyen yaklaşımıdır.",
    question: "FED toplantısında yalnızca faiz kararına mı bakılır?",
    options: ["Evet", "Hayır, açıklamalar ve beklentiler de önemlidir", "Sadece döviz kuruna bakılır"],
    answer: 1,
    explanation: "Gelecek toplantılara ilişkin yönlendirme piyasa fiyatlamasında güçlü rol oynar."
  },
  {
    id: "enflasyon",
    category: "Makro",
    title: "Enflasyon Verisi NASDAQ İçin Neden Kritik?",
    duration: "7 dk",
    level: "Başlangıç",
    summary: "Beklentiden yüksek enflasyon faizlerin daha uzun süre yüksek kalabileceği düşüncesini güçlendirebilir. Bu durum özellikle büyüme hisselerinin değerlemesini baskılayabilir.",
    points: ["Veri beklentiyle kıyaslanır.", "Çekirdek enflasyon yakından izlenir.", "Aylık ve yıllık değişimler farklı bilgi verir."],
    example: "Beklentiyi aşan TÜFE verisi sonrası tahvil faizlerinin yükselmesi NASDAQ üzerinde baskı oluşturabilir.",
    term: "Çekirdek enflasyon",
    definition: "Genellikle oynak gıda ve enerji kalemleri çıkarılarak hesaplanan enflasyon göstergesidir.",
    question: "Enflasyon verisi değerlendirilirken en önemli karşılaştırmalardan biri nedir?",
    options: ["Analist beklentisi", "Şirket logosu", "Hisse kodunun uzunluğu"],
    answer: 0,
    explanation: "Piyasa tepkisi çoğunlukla gerçekleşen verinin beklentiden ne kadar saptığına bağlıdır."
  },
  {
    id: "cesitlendirme",
    category: "Portföy",
    title: "Çeşitlendirme Riski Nasıl Azaltır?",
    duration: "6 dk",
    level: "Başlangıç",
    summary: "Çeşitlendirme sermayeyi farklı şirket, sektör ve varlıklara dağıtarak tek bir olumsuz gelişmenin portföy üzerindeki etkisini sınırlar.",
    points: ["Çok sayıda benzer hisse gerçek çeşitlendirme değildir.", "Sektör dağılımı önemlidir.", "Aşırı çeşitlendirme takibi zorlaştırabilir."],
    example: "Portföydeki tüm hisseler yarı iletkense şirket sayısı fazla olsa bile sektör riski yoğun kalır.",
    term: "Korelasyon",
    definition: "İki varlığın fiyatlarının ne ölçüde birlikte hareket ettiğini gösteren istatistiksel ilişkidir.",
    question: "On farklı teknoloji hissesi her zaman güçlü çeşitlendirme sağlar mı?",
    options: ["Evet, her durumda", "Hayır, aynı sektör riski sürebilir", "Sadece fiyatları aynıysa"],
    answer: 1,
    explanation: "Şirket sayısından çok risk kaynaklarının birbirinden farklı olması önemlidir."
  },
  {
    id: "pozisyon-boyutu",
    category: "Risk",
    title: "Doğru Pozisyon Büyüklüğü Neden Önemlidir?",
    duration: "7 dk",
    level: "Orta",
    summary: "İyi bir analiz bile yanlış pozisyon büyüklüğü nedeniyle portföyde aşırı zarar yaratabilir. Pozisyon büyüklüğü risk toleransı ve zarar durdurma mesafesiyle birlikte düşünülmelidir.",
    points: ["Tek hisseye aşırı ağırlık riski büyütür.", "Oynak hisselerde daha küçük pozisyon düşünülebilir.", "Önceden belirlenen risk duygusal kararları azaltır."],
    example: "Yüzde 20 oynayabilen küçük bir şirkete portföyün çok büyük bölümünü ayırmak toplam riski yükseltir.",
    term: "Pozisyon büyüklüğü",
    definition: "Bir yatırım aracına ayrılan sermayenin tutarı veya portföy içindeki yüzdesidir.",
    question: "Daha oynak bir hissede genel olarak hangi yaklaşım riski sınırlar?",
    options: ["Daha kontrollü pozisyon büyüklüğü", "Tüm portföyü yatırmak", "Riski hiç ölçmemek"],
    answer: 0,
    explanation: "Pozisyon küçüldükçe sert fiyat hareketinin toplam portföy üzerindeki etkisi azalır."
  }
];

export function getDailyLessonIndex(date = new Date()) {
  const start = new Date(date.getFullYear(), 0, 0);
  const dayNumber = Math.floor(
    (date.getTime() - start.getTime()) /
      (24 * 60 * 60 * 1000)
  );

  return Math.abs(dayNumber - 1) %
    ACADEMY_LESSONS.length;
}
